permalink: /blog/:year/:month/:day/:title
description: ""
title: "St. Laurences Anglican Church"
title_long: "St. Laurences Anglican Church"
title_legal: "St. Laurences Anglican Church"
hostname: "cabooltureanglican.org.au"
exclude: ['bin']
markdown: kramdown
gems:
  - jekyll-sitemap
